backend:
  name: github
  repo: renatorocha1/renatorocha.net
  branch: master
  site_domain: https://renatorocha.netlify.app/

publish_mode: editorial_workflow
media_folder: static/assets/images
public_folder: assets/images

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
